### ISSUE TITLE
Historic Options data missing from 0930-1400 every day

### ISSUE THREAD

**Issue by sharkbruhaha** [polygon-io/client-python#296]
**Describe the bug**
When querying for historic options data, there is no data available from 0930-1400 every day.

**To Reproduce**
```python
from polygon import RESTClient
import datetime as dt
import pandas as pd
import plotly.graph_objects as go
from plotly.offline import plot

#api key from config
polygonAPIkey = '<api_key_here>'

client = RESTClient(polygonAPIkey)

contractNames = []
#strike = '320'
strike = '115'
for c in client.list_options_contracts(underlying_ticker = 'GME', contract_type = 'call', expiration_date = '2021-01-29', as_of = '2021-01-29', strike_price = strike, expired = True, limit = 1000): contractNames.append(c)
print(contractNames)

contractData = contractNames[0]

#get options ticker
optionsTicker = contractData.ticker

# 1min pricebars
minuteOptionData = client.get_aggs(ticker = optionsTicker, multiplier = 1, timespan = 'minute', from_ = '2021-01-28', to = '2021-01-30', adjusted = False, limit = 49999)

#list of polygon OptionsContract objects to DataFrame
optionDataFrame = pd.DataFrame(minuteOptionData)

#create Date column
optionDataFrame['Date'] = optionDataFrame['timestamp'].apply(lambda x: pd.to_datetime(x*1000000))

optionDataFrame = optionDataFrame.set_index('Date')

#generate plotly figure
fig = go.Figure(data=[go.Candlestick(x=optionDataFrame.index,
                open=optionDataFrame['open'],
                high=optionDataFrame['high'],
                low=optionDataFrame['low'],
                close=optionDataFrame['close'])])

#open figure in browser
plot(fig, auto_open=True)
```

**Expected behavior**
I expect the entire day's option history to be present, just like it is for the stock prices.

**Screenshots**
Options missing data:
![image](https://user-images.githubusercontent.com/44031572/188560252-8a0333de-d8ef-48e5-814b-32c1afd37cf3.png)
Stocks having the missing time period:
![image](https://user-images.githubusercontent.com/44031572/188560360-91d0a5d5-783b-45c7-a0d6-016ea809703f.png)

**Comment by danielatpolygonio** [comment]
Hi @sharkbruhaha ! Thanks for using our client and our APIs! 

I think the issue has to do with timezones (the bane of my existence). I changed the following under the # create Date column comment and the plots show the expected time range. 
```python
# create Date column
optionDataFrame["Date"] = pd.to_datetime(
    optionDataFrame["timestamp"], unit="ms", utc=True
).dt.tz_convert("US/Eastern")
```

The stocks graph looks more reasonable at first glance I think because we have aggs for extended hours, which go from 4 AM EST to 8 PM EST. Looking at the upper end of the graph though, it extends past midnight, which makes sense as UTC is +5 from EST. 

Let me know if that makes sense!

Options With Change:
![newplot](https://user-images.githubusercontent.com/93154633/188968226-d52996a9-c315-4262-a3de-49f663a0e26e.png)

Stocks With Change:
![newplot (2)](https://user-images.githubusercontent.com/93154633/188968348-225c7ba5-db6c-4f04-ae46-405397067fa4.png)

**Comment by sharkbruhaha** [comment]
ah! thank you for that explanation and code snippet to correct!
