### ISSUE TITLE
Can't get more than 10 days of data for intraday

### ISSUE THREAD

**Issue by makovez** [polygon-io/client-python#387]
```
from polygon import RESTClient
client = RESTClient(api_key="____")

ticker = "AAPL"

# List Aggregates (Bars)
bars = client.get_aggs(ticker=ticker, multiplier=15, timespan="minute", from_="2022-01-10", to="2023-02-10")
for bar in bars:
    print(bar)
```

With this code i only get bars from 10 january 2022 to 19 january 2022
![image](https://user-images.githubusercontent.com/21694707/220386814-155838fe-a0a1-437b-a093-e7cf304fc553.png)

I have the basic plan subscription

**Comment by justinpolygon** [comment]
Hey @makovez, I think what's happening here is that aggregate API has a default limit of 5,000 and a max value of 50,000. So, since you're not calling a limit, you're likely only getting 5,000 minutes of data even though you have a large date range there. We have a blog post here that talks about it: https://polygon.io/blog/aggs-api-updates/

So, even with a max limit of 50,000 you'll likely only be able to fetch a couple months at a time. What I'd suggest it probably getting the max 50,000 limit and then have a loop that goes over each month just to make sure you never hit the limit. Hopefully that makes sense.

**Comment by makovez** [comment]
Thanks yes it was that the problem.

Have a good day
