### ISSUE TITLE
Is there a particular reason `urllib3<2.0.0,>=1.26.9` is required?

### ISSUE THREAD

**Issue by jrosebr1** [polygon-io/client-python#692]
The reason I ask is because a project I'm working on requires `urllib3>=2.0.0`.

I installed `urllib3==2.2.1` and `polygon-api-client` and my codebase and tests still worked (I predominately use only the `get_aggs` method). 

Should I be worried about using `urllib3` v2?

Thanks so much.

**Comment by justinpolygon** [comment]
Hey @jrosebr1. TL;DR -- nothing to be concerned about.

We can probably just update it. When we last looked at it we needed to do some testing to make sure everything still worked as expected so that delayed the release. I think all that's done now so we can go ahead. Thanks for pointing that out. We're going to do a new release shortly here and I'll make sure that's updated too.

Cheers

**Comment by jrosebr1** [comment]
Wow, thanks so much for the quick reply. Really appreciate it 🙏 

I'll keep an eye out for the latest version 😄

**Comment by justinpolygon** [comment]
No worries. I'll keep this open and ping you when it's out. Cheers!

**Comment by justinpolygon** [comment]
Urllib has been updated to 2.x and a new v1.14.0 release published https://github.com/polygon-io/client-python/releases/tag/v1.14.0. Thanks for the suggestion here!

You can upgrade via `pip install -U polygon-api-client`.

**Comment by jrosebr1** [comment]
Thanks so much @justinpolygon! ❤️
