### ISSUE TITLE
Get Sales & Time data of Options

### ISSUE THREAD

**Issue by tiger2014** [polygon-io/client-python#753]
I want to get options' Sales & Time data, it should include ask price, bid price, trade price, trade size. But, according to the document, I must combined the data from trade api and quote api. Could you please offer a single function to return the Sales & Time data?

**Comment by justinpolygon** [comment]
Hey @tiger2014, based on your question, I suspect you might just need the trades data, but I want to provide a more detailed response to cover all possibilities.

At the moment, our Trades API and Quotes API for options provide different types of data:

- The [Trades API](https://polygon.io/docs/options/get_v3_trades__optionsticker) gives you the executed trade data (trade price and trade size).
- The [Quotes API](https://polygon.io/docs/options/get_v3_quotes__optionsticker) gives you the bid and ask prices, along with the size of the quotes.

Currently, we don’t have a single API that returns both the time and sales (trades) data alongside bid/ask quotes in one response. However, you can retrieve the data separately from the respective APIs and combine them on your end.

Additionally, if you're looking to do this for multiple options or want to work with historical data, you might want to consider using our [flat files](https://polygon.io/flat-files). These flat files provide bulk access to both trade and quote data and may be more efficient if you're handling large datasets, rather than making multiple API calls for individual options. For just a single option, the APIs should suffice.

Let me know if that makes sense.

**Comment by justinpolygon** [comment]
I'm going to close this issue for now. If you think this is something that would be a useful feature, please submit it as a request at our product roadmap. The product team is always looking for new ideas, and they'd love to take a look!
